[spa.project.definition]
name = "{{ cookiecutter.project_name }}"
description = "{{ cookiecutter.project_short_description }}"
author = "{{ cookiecutter.author_name }}"
author_email = "{{ cookiecutter.author_email }}"
base_api = "api.yaml"

[spa.template.files]
model = ".spa/templates/models/model.txt"
service = ".spa/templates/models/service.txt"
controller = ".spa/templates/models/controller.txt"
endpoint = ".spa/templates/lambda_endpoint.txt"
lambda_function = ".spa/templates/lambda.txt"
test_lambda = ".spa/templates/test_lambda_function.txt"
lambda_conf = ".spa/templates/lambda_conf.txt"

[spa.project.folders]
root = "src"
models = "src/layers/databases/python/core_db/models"
services = "src/layers/databases/python/core_db/services"
controllers = "src/layers/core/python/core_http/controllers"
jsons = ".spa/templates/json"
lambdas = "src/lambdas"
layers = "src/layers"
