import pulumi
from pulumi import ResourceOptions
from commons import DEFAULT_TAGS

class LambdasStack(pulumi.ComponentResource):
    def __init__(self,
                 name: str,
                 tags: dict,
                 lambda_execution_role_arn: pulumi.Output[str],
                 layers: list[pulumi.Output[str]],
                 sg_ids: list[str],
                 subnets_ids: list[str],
                 opts: ResourceOptions = None
        ):
        super().__init__("{{ cookiecutter.project_name }}:components:lambdasStack", name, {}, opts)

        self.name = name
        self.tags = tags or {}

        # !DANGER: Autogenerated section. Do not edit manually.
